// Shared constants and helpers for the Codex Autorunner package.

// Port the CAR hub web server binds to (matches the upstream default).
export const uiPort = 4173

// Where the 'main' volume is mounted inside the runtime subcontainer.
export const containerDataDir = '/data'

// The CAR hub root lives on the persistent volume.
export const hubDir = `${containerDataDir}/hub`

// Path (relative to the 'main' volume) of the highest-precedence config override
// that CAR reads. We own this file and regenerate it on every startup.
export const hubConfigSubpath = 'hub/.codex-autorunner/config.yml'

// Path (relative to the 'main' volume) of the one-time browser bootstrap token
// CAR writes when it binds to a non-loopback host without a bearer token.
export const bootstrapTokenSubpath = 'hub/.codex-autorunner/bootstrap-token'

// Environment shared by every CAR process so all state lands on the volume.
export const carEnv = {
  HOME: containerDataDir,
  CAR_GLOBAL_STATE_ROOT: `${containerDataDir}/.codex-autorunner`,
  CODEX_HOME: `${containerDataDir}/.codex`,
}

/**
 * Render the CAR server config override. CAR binds TrustedHost/CORS to an
 * explicit allow-list when serving on a non-loopback host, so we feed it the
 * StartOS interface hostnames discovered at runtime.
 */
export const renderHubConfig = (hostnames: string[]): string => {
  const hosts = hostnames.map((h) => `    - ${h}`).join('\n')
  const origins = hostnames
    .flatMap((h) => [`    - https://${h}`, `    - http://${h}`])
    .join('\n')
  return `# Generated by the StartOS wrapper on every startup. Do not edit.
server:
  host: 0.0.0.0
  port: ${uiPort}
  base_path: ""
  access_log: false
  allowed_hosts:
${hosts || '    []'}
  allowed_origins:
${origins || '    []'}
`
}
